// class Autogenerated {
//   Student1Student1? student1Student1;

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     student1Student1 = json['student1 student1'] != null
//         ? Student1Student1.fromJson(json['student1 student1'])
//         : null;
//   }
// }

class Student1Student1 {
  String? fromSurahName;
  int? fromAyah;
  String? toSurahName;
  int? toAyah;
  int? absenceDays;

  Student1Student1.fromJson(Map<String, dynamic> json) {
    fromSurahName = json['from_surah_name'];
    fromAyah = json['from_ayah'];
    toSurahName = json['to_surah_name'];
    toAyah = json['to_ayah'];
    absenceDays = json['absence_days'];
  }
}
